owener_id = 1255875612
bussiness_id = 1882341674
mohsen_id = 417735934
danial_id = 1451463020
nima_id = 382401358
arman_id = 614114940
sheyda_id = 760297985
fatemeh_id = 633922746
mani_id = 1173121917
goli_id = 1262617647
kia_id = 494902830
yehaneh_id = 173307158
fallah_id = 815666122
anita_id = 711964031
matin_id = 710428843
parham_id = 915611725 
parsa_id = 5038808491
hasti_id = 164544638

home_return_txt = "برگشت"

question_subject_keyboard = [["بیوشیمی","سلولی"],
                    ["مولکولی","ژنتیک کلاسیک"],
                    ["تکامل و فیلوژنتیک","سیستماتیک گیاهی"],
                    ["سیستماتیک جانوری","آناتومی گیاهی"],
                    ["فیزیولوژی گیاهی","فیزیولوژی جانوری"],
                    ["فیزیولوژی انسانی","اکولوژی"],
                    ["رفتار شناسی","آمار و ریاضیات زیستی"],
                    ["مشاوره","غیره"],
                    [home_return_txt]]

subjects_check_list = ["بیوشیمی",
                       "سلولی",
                       "مولکولی",
                       "ژنتیک کلاسیک",
                       "تکامل و فیلوژنتیک",
                       "سیستماتیک گیاهی",
                       "سیستماتیک جانوری",
                       "آناتومی گیاهی",
                       "فیزیولوژی گیاهی",
                       "فیزیولوژی جانوری",
                       "فیزیولوژی انسانی",
                       "اکولوژی",
                       "رفتار شناسی",
                       "آمار و ریاضیات زیستی",
                       "مشاوره",
                       "غیره",
                       home_return_txt]

irBO_step_one = {
    1:{"q":6,"a":5},
    2:{"q":8,"a":7},
    3:{"q":10,"a":9},
    4:{"q":12,"a":11},
    5:{"q":14,"a":13},
    6:{"q":16,"a":15},
    7:{"q":18,"a":17},
    8:{"q":20,"a":19},
    9:{"q":22,"a":21},
    10:{"q":4,"a":23},
    11:{"q":26,"a":25},
    12:{"q":28,"a":27},
    13:{"q":30,"a":29},
    14:{"q":32,"a":31},
    15:{"q":34,"a":33},
    16:{"q":36,"a":35},
    17:{"q":38,"a":37},
    18:{"q":40,"a":39},
    19:{"q":42,"a":41},
    20:{"q":44,"a":43},
    21:{"q":51,"a":50},
    22:{"q":53,"a":52},
    23:{"q":55,"a":54},
    24:{"q":56,"a":57},
    25:{"q":58,"a":59}
    }

irBo_step_two = {
    1:{"q":69,"a":None},
    3:{"q":70,"a":None},
    4:{"q":71,"a":None},
    5:{"q":72,"a":None},
    6:{"q":73,"a":None},
    7:{"q":74,"a":None},
    8:{"q":75,"a":None},
    9:{"q":76,"a":None},
    10:{"q":77,"a":None},
    11:{"q":78,"a":None},
    12:{"q":79,"a":None},
    13:{"q":80,"a":None},
    14:{"q":81,"a":None},
    15:{"q":82,"a":None},
    16:{"q":84,"a":83},
    17:{"q":86,"a":85},
    18:{"q":88,"a":87},
    19:{"q":90,"a":89},
    20:{"q":92,"a":91},
    21:{"q":94,"a":93},
    22:{"q":96,"a":95},
    23:{"q":98,"a":97},
    24:{"q":100,"a":99},
    25:{"q":101,"a":102},
    199:{"q":248,"a":249}
    }

IBO_data_dict = {
    1990:103,
    1991:104,
    1993:105,
    1994:106,
    1995:107,
    1996:108,
    1997:109,
    1998:110,
    1999:111,
    2000:112,
    2001:113,
    2002:114,
    2003:115,
    2004:116,
    2005:117,
    2006:118,
    2007:119,
    2008:120,
    2009:121,
    2010:122,
    2011:123,
    2012:124,
    2013:125,
    2014:126,
    2015:127,
    2016:128,
    2017:129,
    2018:130,
    2019:131,
    2020:132
}
talaha_data_dict = {
    7:{"q":251,"a":None},
    10:{"q":252,"a":None},
    11:{"q":254,"a":253},
    12:{"q":256,"a":255},
    13:{"q":258,"a":257},
    14:{"q":259,"a":None},
    15:{"q":261,"a":260},
    16:{"q":263,"a":262},
    17:{"q":266,"a":265},
    18:{"q":268,"a":267},
    19:{"q":269,"a":None},
    20:{"q":270,"a":None},
    21:{"q":272,"a":271},
    22:{"q":274,"a":273},
    24:{"q":276,"a":275},
}
book_subject_callback = {
    "زیست شناسی عمومی":"bgb",
    "بیوشیمی":"bch",
    "سلولی":"bce",
    "مولکولی":"bmo",
    "ژنتیک کلاسیک":"bcg",
    "تکامل و فیلوژنتیک":"bep",
    "سیستماتیک گیاهی":"bps",
    "سیستماتیک جانوری":"bas",
    "آناتومی گیاهی":"bpa",
    "فیزیولوژی گیاهی":"bpp",
    "فیزیولوژی جانوری":"bap",
    "فیزیولوژی انسانی":"bhp",
    "اکولوژی":"bec",
    "رفتار شناسی":"bbe",
    "آمار و ریاضیات زیستی":"bma",
    "آزمایشگاه":"bla",
    "بیوانفورماتیک":"bin"
}

inv_book_subject_callback = {v: k for k, v in book_subject_callback.items()}

subjects_books_list = {
    "زیست شناسی عمومی":["Campbell Biology","Solomon Biology","Life Biology","Raven Biology"],
    "بیوشیمی":["Lehninger","Lehninger answer","Stryer","Voet","Harper","Enzyme Kinetic","Grisham","Grisham answer","Biochemical Calculations"],
    "سلولی":["Lodish", "Lewins", "The Cell", "Essential cell biology","The problem book of the cell","جواب های امیری"],
    "مولکولی":["Watson", "Weaver", "Genes XI"],
    "ژنتیک کلاسیک":["Griffiths", "Griffiths answer", "Kowles", "Stansfield", "Wellnitz","جواب های شاهنظر"],
    "تکامل و فیلوژنتیک":["Bergstrom","Futuyama","Herron","Phylogenetic Handbook"],
    "سیستماتیک گیاهی":["Plant Systematics 2nd edition","Plant Systematics 3rd edition"],
    "سیستماتیک جانوری":["Hickman","Brusca","Kardong","جانورشناسی مقایسه ای"],
    "آناتومی گیاهی":["Raven Plants","Crang","Stern","Rost","Esaus","Microscope Pic","Color Atlas of Plant Structure"],
    "فیزیولوژی گیاهی":["Taiz and Zieger"],
    "فیزیولوژی جانوری":["Moyes", "Eckert","Hill"],
    "فیزیولوژی انسانی":["Guyton","Junqueira","Ganong","Saladin","Langman","Kandel","Case and problems","Berne and Levy","Color Atlas of Physiology","Problem-Based Physiology",
                        "Problem-Based Physiology Fluid, Electrolyte & Acid-Base","Problem-Based Physiology Neurophysiology, Gastrointestinal & Endocrine Systems",
                        "Problem-Based Physiology Cardio, Respiratory & Renal Systems"],
    "اکولوژی":["Krebs","Primer","Rockwood","Elements of ecology","Molles"],
    "رفتار شناسی":["Krebs and Davies","Dugantin","Aubrey manning"],
    "آمار و ریاضیات زیستی":["Calculus for Biology and Medicine","Daniel", "Bernard", "Jerrold", "Sylvia"],
    "آزمایشگاه":["Biology Lab Manual","Photographic Atlas"],
    "بیوانفورماتیک":["Jin Xiong","Bioinformatics and Functional Genomics","Biological Sequence Analysis","Understanding Bioinformatics"]
}

books_message_id_dict = {
    "Campbell Biology":159,
    "Campbell Biology Test Bank":225,
    "GRE Biology Test":221,
    "Solomon Biology":202,
    "Life Biology":211,
    "Raven Biology":197,
    "Lehninger":165,
    "Lehninger answer":172,
    "Stryer":164,
    "Voet":141,
    "Harper":205,
    "Enzyme Kinetic":185,
    "Grisham":181,
    "Grisham answer":180,
    "Biochemical Calculations":148,
    "Lodish":149,
    "Lewins":212,
    "The Cell":150,
    "Essential cell biology":220,
    "The problem book of the cell":160,
    "جواب های امیری":161,
    "جواب های شاهنظر":247,
    "Watson":142,
    "Weaver":177,
    "Genes XI":179,
    "Griffiths":203,
    "Griffiths answer":171,
    "Kowles":196,
    "Stansfield":163,
    "Wellnitz":201,
    "Bergstrom":218,
    "Futuyama":152,
    "Herron":187,
    "Phylogenetic Handbook":241,
    "Plant Systematics 2nd edition":137,
    "Plant Systematics 3rd edition":138,
    "Hickman":186,
    "Brusca":193,
    "Kardong":158,
    "جانورشناسی مقایسه ای":157,
    "Raven Plants":144,
    "Crang":140,
    "Stern":174,
    "Rost":198,
    "Esaus":199,
    "Microscope Pic":136,
    "Color Atlas of Plant Structure":145,
    "Taiz and Zieger":190,
    "Moyes":135,
    "Eckert":191,
    "Hill":184,
    "Guyton":154,
    "Junqueira":189,
    "Ganong":188,
    "Saladin":214,
    "Langman":204,
    "Kandel":206,
    "Case and problems":156,
    "Berne and Levy":153,
    "Krebs":168,
    "Primer":219,
    "Rockwood":146,
    "Dugantin":176,
    "Elements of ecology":215,
    "Molles":147,
    "Krebs and Davies":217,
    "Aubrey manning":246,
    "Calculus for Biology and Medicine":139,
    "Daniel":207,
    "Bernard":208,
    "Jerrold":209,
    "Sylvia":210,
    "Biology Lab Manual":194,
    "Photographic Atlas":195,
    "Problem-Based Physiology Fluid, Electrolyte & Acid-Base":232,
    "Problem-Based Physiology Neurophysiology, Gastrointestinal & Endocrine Systems":234,
    "Problem-Based Physiology Cardio, Respiratory & Renal Systems":235,
    "Problem-Based Physiology":237,
    "Color Atlas of Physiology":239,
    "Thieme Test Physiology":240,
    "Jin Xiong":244,
    "Bioinformatics and Functional Genomics":242,
    "Biological Sequence Analysis":243,
    "Understanding Bioinformatics":245
}

question_books_and_manual_list = [
    "Campbell Biology Test Bank",
    "GRE Biology Test",
    "The problem book of the cell",
    "Lehninger answer",
    "جواب های شاهنظر",
    "جواب های امیری",
    "Biochemical Calculations",
    "Grisham answer",
    "Griffiths answer",
    "Case and problems",
    "Problem-Based Physiology",
    "Problem-Based Physiology Fluid, Electrolyte & Acid-Base",
    "Problem-Based Physiology Neurophysiology, Gastrointestinal & Endocrine Systems",
    "Problem-Based Physiology Cardio, Respiratory & Renal Systems",
    "Thieme Test Physiology",
    ]

other_country_list = {
    "المپیاد داخلی استرالیا":"ocasoe",
    "المپیاد کانادا":"ocbiocomp",
    "کانتست هنگ کنک":"ochoko",
    "المپیاد داخلی هند":"ocinbo",
    "مسابقات مندل":"ocmbio",
    "المپیاد داخلی نیوزلند":"ocnzibo",
    "مرحله اوپن آمریکا":"ocusaboo",
    "مرحله نیمه نهایی آمریکا":"ocusabos",
    "آزمون 1.99":"M2_199"
}

other_country_message_id = {
    "asoe":223,
    "biocomp":224,
    "hoko":226,
    "inbo":227,
    "mbio":228,
    "nzibo":229,
    "usaboo":230,
    "usabos":231,
}

q_subject_tanslator = {"بیوشیمی":"00",
                       "سلولی":"01",
                       "مولکولی":"02",
                       "ژنتیک_کلاسیک":"03",
                       "تکامل_و_فیلوژنتیک":"04",
                       "سیستماتیک_گیاهی":"05",
                       "سیستماتیک_جانوری":"06",
                       "آتاتومی_گیاهی":"07",
                       "فیزیولوژی_گیاهی":"08",
                       "فیزیولوژی_جانوری":"09",
                       "فیزیولوژی_انسانی":"10",
                       "اکولوژی":"11",
                       "رفتار_شناسی":"12",
                       "آمار_و_ریاضیات_زیستی":"13",
                       "مشاوره":"14",
                       "غیره":"15"}

inv_q_subject_tanslator = {v: k for k, v in q_subject_tanslator.items()}
